"""Canonical versioned contracts (``<Name>/v1``) and their registry."""

from apiforge.contracts.adapter import (
    AdapterCapability,
    AdapterExecution,
    AdapterMode,
    AdapterStatus,
    EvidenceLevel,
)
from apiforge.contracts.compatibility import CompatibilityCell, CompatibilityMatrix, RuntimeReceipt
from apiforge.contracts.context import ContextResult, ContextScope, ContextTarget
from apiforge.contracts.data_runtime import DataProvider, DataReadReceipt, DataReadRequest
from apiforge.contracts.debate import (
    AdaptivePlan,
    AdaptivePolicy,
    DebateReplay,
    ParticipantDeclaration,
)
from apiforge.contracts.devin import (
    DevinCheck,
    DevinCliProbe,
    DevinLaunch,
    DevinPayload,
    DevinPermissionMode,
    DevinPromptTransport,
    DevinSurface,
    DevinTaskKind,
)
from apiforge.contracts.distribution import (
    AssetStatus,
    CapabilityDiagnostic,
    DistributionDoctor,
    DistributionRefusal,
    ForgePaths,
)
from apiforge.contracts.evidence import EvidenceKind, EvidenceRecord, EvidenceRef
from apiforge.contracts.experience import ExperienceAction, ExperienceSnapshot, ExperienceView
from apiforge.contracts.host import (
    HostCapability,
    HostCapabilityRequest,
    HostDeclaration,
    HostResolution,
)
from apiforge.contracts.integration import (
    ExternalReadReceipt,
    ExternalReadRequest,
    ExternalReadResult,
    GitHubPrReceipt,
)
from apiforge.contracts.knowledge import (
    ExpertisePack,
    FreshnessResult,
    KnowledgeObservation,
    PackFreshness,
    SourceObservation,
)
from apiforge.contracts.platform import (
    CapabilityRecord,
    CapabilityRequest,
    CapabilityResult,
    PlatformRuntimeReceipt,
    VerticalCoverage,
    VerticalRuntimeReceipt,
)
from apiforge.contracts.routing import (
    CandidateAssessment,
    ObservedSignal,
    RoutingDecision,
    RoutingPlan,
    RoutingPolicy,
    RoutingRequest,
    ScorecardFeedback,
)
from apiforge.contracts.routing_evolution import (
    EvidenceCoverage,
    EvolutionMode,
    EvolutionPolicy,
    PromotionGate,
    PromotionState,
    RoutingEvolution,
)
from apiforge.contracts.sandbox import SandboxCommand, SandboxCommandResult
from apiforge.contracts.workspace import (
    ProjectManifest,
    RepositoryRef,
    WorkspaceGraph,
    WorkspaceManifest,
    WorkspaceRelation,
    WorkspaceStatus,
)

__all__ = [
    "AdapterCapability",
    "AdapterExecution",
    "AdapterMode",
    "AdapterStatus",
    "AdaptivePlan",
    "AdaptivePolicy",
    "AssetStatus",
    "CandidateAssessment",
    "CapabilityDiagnostic",
    "CapabilityRecord",
    "CapabilityRequest",
    "CapabilityResult",
    "CompatibilityCell",
    "CompatibilityMatrix",
    "ContextResult",
    "ContextScope",
    "ContextTarget",
    "DataProvider",
    "DataReadReceipt",
    "DataReadRequest",
    "DebateReplay",
    "DevinCheck",
    "DevinCliProbe",
    "DevinLaunch",
    "DevinPayload",
    "DevinPermissionMode",
    "DevinPromptTransport",
    "DevinSurface",
    "DevinTaskKind",
    "DistributionDoctor",
    "DistributionRefusal",
    "EvidenceCoverage",
    "EvidenceKind",
    "EvidenceLevel",
    "EvidenceRecord",
    "EvidenceRef",
    "EvolutionMode",
    "EvolutionPolicy",
    "ExperienceAction",
    "ExperienceSnapshot",
    "ExperienceView",
    "ExpertisePack",
    "ExternalReadReceipt",
    "ExternalReadRequest",
    "ExternalReadResult",
    "ForgePaths",
    "FreshnessResult",
    "GitHubPrReceipt",
    "HostCapability",
    "HostCapabilityRequest",
    "HostDeclaration",
    "HostResolution",
    "KnowledgeObservation",
    "ObservedSignal",
    "PackFreshness",
    "ParticipantDeclaration",
    "PlatformRuntimeReceipt",
    "ProjectManifest",
    "PromotionGate",
    "PromotionState",
    "RepositoryRef",
    "RoutingDecision",
    "RoutingEvolution",
    "RoutingPlan",
    "RoutingPolicy",
    "RoutingRequest",
    "RuntimeReceipt",
    "SandboxCommand",
    "SandboxCommandResult",
    "ScorecardFeedback",
    "SourceObservation",
    "VerticalCoverage",
    "VerticalRuntimeReceipt",
    "WorkspaceGraph",
    "WorkspaceManifest",
    "WorkspaceRelation",
    "WorkspaceStatus",
]
