"""The contract registry: ``<Name>/v1`` -> model class, introspectable."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from apiforge.contracts.agent_telemetry import (
    AgentSpan,
    AgentSpanQuery,
    AgentSpanResult,
    CorrelationIds,
)
from apiforge.contracts.agentic import (
    AgentArtifact,
    AgenticPolicy,
    AgenticRun,
    AgentInvocation,
    ApprovalGate,
    DecisionRecord,
    HandoffRecord,
    RuntimeReview,
    TrajectoryEvent,
)
from apiforge.contracts.agentic_governance import (
    AgenticBudgetPlan,
    BudgetDecision,
    BudgetLimit,
    BudgetSpend,
    ControlPlaneRoute,
    DecisionGateResult,
    DecisionRequest,
    ExpectedInformationGain,
    FallbackDecision,
    GovernorDecision,
    GovernorInputs,
    LoopDetection,
    PromotionDecision,
    PromotionEvidence,
    RecoveryDecision,
    RouteDecision,
    RunGovernanceContext,
    ShadowRecord,
    StopDecision,
)
from apiforge.contracts.agentic_health import AgenticDoctorReport, AgenticDoctorSection
from apiforge.contracts.agentic_memory import (
    BlackboardEntry,
    BlackboardQuery,
    BlackboardResult,
    MemoryCandidate,
    MemoryInvalidation,
    MemoryOutcome,
    MemoryPolicy,
    MemoryQuery,
    MemoryRecord,
    MemoryRetrievalResult,
    MemoryTrust,
    SemanticCheckpoint,
)
from apiforge.contracts.agentops_report import (
    ComparisonAxis,
    InspectionMetric,
    InspectionSection,
    RunComparison,
    RunInspection,
    WasteFinding,
    WasteReport,
)
from apiforge.contracts.base import ContractError
from apiforge.contracts.cache import CacheDecision, CacheDep, CacheEntry, DeltaSlice
from apiforge.contracts.context import (
    CapsuleBudget,
    CapsuleRefusal,
    ContextCapsule,
    ContextRef,
    ContextScope,
)
from apiforge.contracts.context_quality import (
    ContextQualityMetric,
    ContextQualityReport,
    ContextSufficiencyResult,
    ContextUseRecord,
    RoleContextPolicy,
    RoleContextQuality,
    RoleContextTelemetry,
)
from apiforge.contracts.core import (
    ActionPlan,
    ActionStep,
    ArtifactRef,
    Decision,
    Verification,
)
from apiforge.contracts.devin import DevinCheck, DevinCliProbe, DevinLaunch, DevinPayload
from apiforge.contracts.distribution import DistributionDoctor
from apiforge.contracts.economy import (
    BudgetEnvelope,
    CostVector,
    EconomyPlan,
    LadderStep,
    LedgerRef,
    ProofReceipt,
    RiskClassification,
    RunLedgerEntry,
)
from apiforge.contracts.economy_evals import (
    BenchmarkIdentity,
    EconomyMatrix,
    EvaluationGate,
    InformationGain,
    ReplayReport,
    RoleROI,
)
from apiforge.contracts.economy_extras import (
    EconomyDoctor,
    EvidenceNode,
    LocalityPlan,
    PromptEnvelope,
    ProviderCapability,
    RetrievalResult,
    TierDecision,
    VerificationPlan,
)
from apiforge.contracts.economy_resume import (
    EconomyCheckpoint,
    FreshnessWatch,
    LiveEvidenceDecision,
    PhaseBudgetPlan,
    VerificationEscalation,
)
from apiforge.contracts.eval_plane import (
    AdversarialCaseResult,
    FrontierPoint,
    LiveEvalLayer,
    LiveEvalReport,
    MemoryEvalCaseResult,
    MemoryEvalReport,
    QualityFrontier,
    SecurityAdversarialReport,
    TraceGrade,
    TraceGradeDimension,
    TraceGradingReport,
)
from apiforge.contracts.evidence import EvidenceRef
from apiforge.contracts.forge_protocol import (
    ForgeCapabilityDescriptor,
    ForgeEvidenceArtifact,
    ForgeEvidenceBundle,
    ForgeHandoff,
    ForgeHealth,
    ForgeTaskRequest,
    ForgeTaskResult,
    ForgeTaskStatus,
)
from apiforge.contracts.graph import GraphEdge, GraphExport, GraphNode
from apiforge.contracts.graph_access import GraphAccessIR, GraphPlanIR
from apiforge.contracts.graph_impact import (
    GraphCandidateImpact,
    GraphImpactAssessment,
    GraphImpactEffect,
    GraphImpactNode,
    GraphImpactPolicy,
)
from apiforge.contracts.grpc import (
    GrpcArtifact,
    GrpcCapability,
    GrpcCodegenRequest,
    GrpcCodegenResult,
    GrpcCompatibilityReport,
    GrpcDiagnostic,
    GrpcGatewayProjection,
    GrpcGatewayRequest,
    GrpcIR,
    GrpcMessage,
    GrpcPerformanceReport,
    GrpcPerformanceRun,
    GrpcPlan,
    GrpcRpc,
    GrpcRuntimePolicy,
    GrpcSecurityReport,
    GrpcService,
    GrpcVerification,
)
from apiforge.contracts.integration import (
    ExternalReadReceipt,
    ExternalReadRequest,
    ExternalReadResult,
    GitHubPrReceipt,
)
from apiforge.contracts.knowledge import (
    ExpertisePack,
    KnowledgeDrift,
    KnowledgeImpactReport,
    PackApplicability,
)
from apiforge.contracts.lab import LabReport, LabScenario
from apiforge.contracts.model_routing import (
    AdaptiveRetrievalResult,
    ModelCandidate,
    ModelEvaluation,
    ModelRouteDecision,
    ModelRouteInputs,
    ModelScorecard,
    QueryRewrite,
    RankedModel,
    RetrievalComparison,
    RetrievalStep,
)
from apiforge.contracts.observability import (
    Capability,
    CircuitBreakerEvent,
    CircuitBreakerMetrics,
    CircuitBreakerPolicy,
    CircuitMetricsExportReceipt,
    HostExportBinding,
    IntentDiff,
    ObservabilityExportReadiness,
    ObservabilityFinding,
    ObservationSnapshot,
    OperationReceipt,
    ReadRetryPolicy,
    ReadSafetyPolicy,
    SignalSummary,
    SLODefinition,
    SLOResult,
    TelemetryRecord,
    VendorIntent,
)
from apiforge.contracts.otel_export import CollectorProbe, OtlpExport, OtlpValidation
from apiforge.contracts.platform import (
    CapabilityRecord,
    CapabilityRequest,
    CapabilityResult,
    PlatformRuntimeReceipt,
    VerticalCoverage,
    VerticalRuntimeReceipt,
)
from apiforge.contracts.risk_complexity import RiskComplexityAssessment
from apiforge.contracts.routing import (
    CandidateAssessment,
    ObservedSignal,
    RoutingDecision,
    RoutingPlan,
    RoutingPolicy,
    RoutingRequest,
    ScorecardFeedback,
)
from apiforge.contracts.routing_evolution import (
    EvidenceCoverage,
    EvolutionPolicy,
    PromotionGate,
    RoutingEvolution,
)
from apiforge.contracts.scorecard_routing import (
    ScorecardCandidateAssessment,
    ScorecardRoutingAssessment,
    ScorecardRoutingPolicy,
)
from apiforge.contracts.scorecard_shadow import ScorecardShadowEvaluation
from apiforge.contracts.selective import (
    AgentUniqueness,
    ExpertiseSelection,
    PositionDelta,
    RefereePacket,
    RoleContextPlan,
    ShadowDecision,
)
from apiforge.contracts.stubs import (
    AgenticQualityAssessment,
    AnalyticalAccessIR,
    ApiSafetyAssessment,
    CapacityAssessment,
    DataAccessIR,
    DataAccessReadiness,
    DataPerformanceProfile,
    MessagingAccessIR,
    PerformanceRun,
    RuntimeMatrix,
    StreamingAccessIR,
    TelemetryEvent,
    TestRecord,
    WorkloadProfile,
)
from apiforge.contracts.task import (
    AcceptanceRecord,
    CapabilityProof,
    OutcomeBrief,
    TaskHandoff,
    TaskPlan,
    TaskRevision,
    TaskSpec,
)
from apiforge.contracts.token_economics import (
    BudgetReconciliation,
    ProviderCost,
    ProviderPricing,
    ReconciliationAxis,
    TokenAccounting,
    TokenLedger,
    TokenLedgerEntry,
    TokenTotals,
)
from apiforge.contracts.tool_host import (
    ErrorSlice,
    HostProjection,
    TestSlice,
    ToolSurface,
)
from apiforge.contracts.tool_surface import (
    DisclosurePolicy,
    PageWindow,
    SurfaceFinding,
    ToolBenchmark,
    ToolBenchmarkReport,
    ToolBenchmarkSample,
    ToolDisclosure,
    ToolPage,
    ToolSurfaceAudit,
)
from apiforge.contracts.trust import (
    AgentPermissionSet,
    MemoryGateResult,
    MemoryInvalidationPlan,
    MemoryQuarantine,
    MemoryRankedResult,
    MemoryScore,
    ToolAuthorization,
    ToolRiskProfile,
    TrustedRef,
    TrustPropagation,
    TrustUnit,
)
from apiforge.contracts.verification import (
    HoldoutRecord,
    VerificationCheck,
    VerificationRecord,
)
from apiforge.contracts.workspace import ProjectManifest, WorkspaceGraph, WorkspaceManifest
from apiforge.core.models import Fact, Finding
from apiforge.evidence.models import Receipt
from apiforge.migration.contracts import (
    DiscoveryResult,
    MigrationFinding,
    MigrationPlan,
    MigrationReadiness,
    MigrationReport,
    MigrationSpec,
    MigrationTask,
    RuntimeCapability,
)

CONTRACTS: dict[str, type[BaseModel]] = {
    "ArtifactRef/v1": ArtifactRef,
    "Fact/v1": Fact,
    "Finding/v1": Finding,
    "Receipt/v1": Receipt,
    "Decision/v1": Decision,
    "ActionPlan/v1": ActionPlan,
    "ActionStep/v1": ActionStep,
    "Verification/v1": Verification,
    "DevinCheck/v1": DevinCheck,
    "DevinCliProbe/v1": DevinCliProbe,
    "DevinLaunch/v1": DevinLaunch,
    "DevinPayload/v1": DevinPayload,
    "TaskSpec/v1": TaskSpec,
    "TaskRevision/v1": TaskRevision,
    "TaskPlan/v1": TaskPlan,
    "TaskHandoff/v1": TaskHandoff,
    "AcceptanceRecord/v1": AcceptanceRecord,
    "CapabilityProof/v1": CapabilityProof,
    "OutcomeBrief/v1": OutcomeBrief,
    "GraphNode/v1": GraphNode,
    "GraphEdge/v1": GraphEdge,
    "GraphExport/v1": GraphExport,
    "GraphAccessIR/v1": GraphAccessIR,
    "GraphPlanIR/v1": GraphPlanIR,
    "GraphImpactPolicy/v1": GraphImpactPolicy,
    "GraphImpactEffect/v1": GraphImpactEffect,
    "GraphImpactNode/v1": GraphImpactNode,
    "GraphCandidateImpact/v1": GraphCandidateImpact,
    "GraphImpactAssessment/v1": GraphImpactAssessment,
    "TelemetryEvent/v1": TelemetryEvent,
    "PerformanceRun/v1": PerformanceRun,
    "CapacityAssessment/v1": CapacityAssessment,
    "DataAccessIR/v1": DataAccessIR,
    "DataAccessReadiness/v1": DataAccessReadiness,
    "DataPerformanceProfile/v1": DataPerformanceProfile,
    "MessagingAccessIR/v1": MessagingAccessIR,
    "StreamingAccessIR/v1": StreamingAccessIR,
    "ApiSafetyAssessment/v1": ApiSafetyAssessment,
    "AgenticQualityAssessment/v1": AgenticQualityAssessment,
    "AnalyticalAccessIR/v1": AnalyticalAccessIR,
    "RuntimeMatrix/v1": RuntimeMatrix,
    "WorkloadProfile/v1": WorkloadProfile,
    "TestRecord/v1": TestRecord,
    "VerificationRecord/v1": VerificationRecord,
    "VerificationCheck/v1": VerificationCheck,
    "HoldoutRecord/v1": HoldoutRecord,
    "AgenticRun/v1": AgenticRun,
    "RuntimeReview/v1": RuntimeReview,
    "AgenticRuntime/v1": AgenticRun,
    "AgenticPolicy/v1": AgenticPolicy,
    "AgentInvocation/v1": AgentInvocation,
    "AgentArtifact/v1": AgentArtifact,
    "HandoffRecord/v1": HandoffRecord,
    "DecisionRecord/v1": DecisionRecord,
    "ApprovalGate/v1": ApprovalGate,
    "TrajectoryEvent/v1": TrajectoryEvent,
    "MemoryTrust/v1": MemoryTrust,
    "MemoryRecord/v1": MemoryRecord,
    "MemoryCandidate/v1": MemoryCandidate,
    "MemoryPolicy/v1": MemoryPolicy,
    "MemoryQuery/v1": MemoryQuery,
    "MemoryOutcome/v1": MemoryOutcome,
    "MemoryRetrievalResult/v1": MemoryRetrievalResult,
    "MemoryInvalidation/v1": MemoryInvalidation,
    "BlackboardEntry/v1": BlackboardEntry,
    "BlackboardQuery/v1": BlackboardQuery,
    "BlackboardResult/v1": BlackboardResult,
    "SemanticCheckpoint/v1": SemanticCheckpoint,
    "BudgetLimit/v1": BudgetLimit,
    "AgenticBudgetPlan/v1": AgenticBudgetPlan,
    "BudgetSpend/v1": BudgetSpend,
    "BudgetDecision/v1": BudgetDecision,
    "AgentSpan/v1": AgentSpan,
    "AgentSpanQuery/v1": AgentSpanQuery,
    "AgentSpanResult/v1": AgentSpanResult,
    "DecisionRequest/v1": DecisionRequest,
    "DecisionGateResult/v1": DecisionGateResult,
    "TelemetryRecord/v1": TelemetryRecord,
    "ObservationSnapshot/v1": ObservationSnapshot,
    "SLODefinition/v1": SLODefinition,
    "SignalSummary/v1": SignalSummary,
    "SLOResult/v1": SLOResult,
    "Capability/v1": Capability,
    "CapabilityRecord/v1": CapabilityRecord,
    "CapabilityRequest/v1": CapabilityRequest,
    "CapabilityResult/v1": CapabilityResult,
    "VerticalCoverage/v1": VerticalCoverage,
    "VerticalRuntimeReceipt/v1": VerticalRuntimeReceipt,
    "ObservedSignal/v1": ObservedSignal,
    "RoutingPolicy/v1": RoutingPolicy,
    "RoutingRequest/v1": RoutingRequest,
    "CandidateAssessment/v1": CandidateAssessment,
    "RoutingDecision/v1": RoutingDecision,
    "RoutingPlan/v1": RoutingPlan,
    "RiskComplexityAssessment/v1": RiskComplexityAssessment,
    "ScorecardRoutingPolicy/v1": ScorecardRoutingPolicy,
    "ScorecardCandidateAssessment/v1": ScorecardCandidateAssessment,
    "ScorecardRoutingAssessment/v1": ScorecardRoutingAssessment,
    "ScorecardShadowEvaluation/v1": ScorecardShadowEvaluation,
    "ExpertisePack/v1": ExpertisePack,
    "KnowledgeDrift/v1": KnowledgeDrift,
    "KnowledgeImpactReport/v1": KnowledgeImpactReport,
    "PackApplicability/v1": PackApplicability,
    "AgenticDoctorReport/v1": AgenticDoctorReport,
    "AgenticDoctorSection/v1": AgenticDoctorSection,
    "LabReport/v1": LabReport,
    "LabScenario/v1": LabScenario,
    "ScorecardFeedback/v1": ScorecardFeedback,
    "EvidenceRef/v1": EvidenceRef,
    "EvidenceCoverage/v1": EvidenceCoverage,
    "EvolutionPolicy/v1": EvolutionPolicy,
    "PromotionGate/v1": PromotionGate,
    "RoutingEvolution/v1": RoutingEvolution,
    "PlatformRuntimeReceipt/v1": PlatformRuntimeReceipt,
    "ExternalReadRequest/v1": ExternalReadRequest,
    "ExternalReadReceipt/v1": ExternalReadReceipt,
    "ExternalReadResult/v1": ExternalReadResult,
    "GitHubPrReceipt/v1": GitHubPrReceipt,
    "VendorIntent/v1": VendorIntent,
    "IntentDiff/v1": IntentDiff,
    "OperationReceipt/v1": OperationReceipt,
    "ObservabilityFinding/v1": ObservabilityFinding,
    "ReadSafetyPolicy/v1": ReadSafetyPolicy,
    "ReadRetryPolicy/v1": ReadRetryPolicy,
    "CircuitBreakerPolicy/v1": CircuitBreakerPolicy,
    "CircuitBreakerEvent/v1": CircuitBreakerEvent,
    "CircuitBreakerMetrics/v1": CircuitBreakerMetrics,
    "CircuitMetricsExportReceipt/v1": CircuitMetricsExportReceipt,
    "HostExportBinding/v1": HostExportBinding,
    "ObservabilityExportReadiness/v1": ObservabilityExportReadiness,
    "GrpcIR/v1": GrpcIR,
    "GrpcMessage/v1": GrpcMessage,
    "GrpcRpc/v1": GrpcRpc,
    "GrpcService/v1": GrpcService,
    "GrpcDiagnostic/v1": GrpcDiagnostic,
    "GrpcCompatibilityReport/v1": GrpcCompatibilityReport,
    "GrpcCapability/v1": GrpcCapability,
    "GrpcCodegenRequest/v1": GrpcCodegenRequest,
    "GrpcCodegenResult/v1": GrpcCodegenResult,
    "GrpcArtifact/v1": GrpcArtifact,
    "GrpcGatewayRequest/v1": GrpcGatewayRequest,
    "GrpcGatewayProjection/v1": GrpcGatewayProjection,
    "GrpcRuntimePolicy/v1": GrpcRuntimePolicy,
    "GrpcPerformanceRun/v1": GrpcPerformanceRun,
    "GrpcPerformanceReport/v1": GrpcPerformanceReport,
    "GrpcSecurityReport/v1": GrpcSecurityReport,
    "GrpcPlan/v1": GrpcPlan,
    "GrpcVerification/v1": GrpcVerification,
    "MigrationSpec/v1": MigrationSpec,
    "RuntimeCapability/v1": RuntimeCapability,
    "MigrationFinding/v1": MigrationFinding,
    "DiscoveryResult/v1": DiscoveryResult,
    "MigrationReadiness/v1": MigrationReadiness,
    "MigrationTask/v1": MigrationTask,
    "MigrationPlan/v1": MigrationPlan,
    "MigrationReport/v1": MigrationReport,
    "Distribution/v1": DistributionDoctor,
    "ProjectManifest/v1": ProjectManifest,
    "WorkspaceManifest/v1": WorkspaceManifest,
    "ArchitectureGraph/v1": WorkspaceGraph,
    "ContextScope/v1": ContextScope,
    "ContextRef/v1": ContextRef,
    "CapsuleBudget/v1": CapsuleBudget,
    "CapsuleRefusal/v1": CapsuleRefusal,
    "ContextCapsule/v1": ContextCapsule,
    "ContextUseRecord/v1": ContextUseRecord,
    "ContextQualityMetric/v1": ContextQualityMetric,
    "ContextQualityReport/v1": ContextQualityReport,
    "ContextSufficiencyResult/v1": ContextSufficiencyResult,
    "RoleContextPolicy/v1": RoleContextPolicy,
    "RoleContextQuality/v1": RoleContextQuality,
    "RoleContextTelemetry/v1": RoleContextTelemetry,
    "TrustUnit/v1": TrustUnit,
    "TrustedRef/v1": TrustedRef,
    "TrustPropagation/v1": TrustPropagation,
    "ToolRiskProfile/v1": ToolRiskProfile,
    "AgentPermissionSet/v1": AgentPermissionSet,
    "ToolAuthorization/v1": ToolAuthorization,
    "MemoryGateResult/v1": MemoryGateResult,
    "MemoryQuarantine/v1": MemoryQuarantine,
    "MemoryInvalidationPlan/v1": MemoryInvalidationPlan,
    "MemoryScore/v1": MemoryScore,
    "MemoryRankedResult/v1": MemoryRankedResult,
    "TokenAccounting/v1": TokenAccounting,
    "TokenLedgerEntry/v1": TokenLedgerEntry,
    "TokenTotals/v1": TokenTotals,
    "TokenLedger/v1": TokenLedger,
    "ProviderPricing/v1": ProviderPricing,
    "ProviderCost/v1": ProviderCost,
    "ReconciliationAxis/v1": ReconciliationAxis,
    "BudgetReconciliation/v1": BudgetReconciliation,
    "GovernorInputs/v1": GovernorInputs,
    "GovernorDecision/v1": GovernorDecision,
    "ExpectedInformationGain/v1": ExpectedInformationGain,
    "StopDecision/v1": StopDecision,
    "RecoveryDecision/v1": RecoveryDecision,
    "LoopDetection/v1": LoopDetection,
    "ControlPlaneRoute/v1": ControlPlaneRoute,
    "ShadowRecord/v1": ShadowRecord,
    "PromotionEvidence/v1": PromotionEvidence,
    "PromotionDecision/v1": PromotionDecision,
    "FallbackDecision/v1": FallbackDecision,
    "RouteDecision/v1": RouteDecision,
    "RunGovernanceContext/v1": RunGovernanceContext,
    "ModelRouteInputs/v1": ModelRouteInputs,
    "ModelCandidate/v1": ModelCandidate,
    "ModelEvaluation/v1": ModelEvaluation,
    "ModelScorecard/v1": ModelScorecard,
    "RankedModel/v1": RankedModel,
    "ModelRouteDecision/v1": ModelRouteDecision,
    "RetrievalStep/v1": RetrievalStep,
    "AdaptiveRetrievalResult/v1": AdaptiveRetrievalResult,
    "QueryRewrite/v1": QueryRewrite,
    "RetrievalComparison/v1": RetrievalComparison,
    "CorrelationIds/v1": CorrelationIds,
    "OtlpExport/v1": OtlpExport,
    "OtlpValidation/v1": OtlpValidation,
    "CollectorProbe/v1": CollectorProbe,
    "RunInspection/v1": RunInspection,
    "InspectionSection/v1": InspectionSection,
    "InspectionMetric/v1": InspectionMetric,
    "WasteFinding/v1": WasteFinding,
    "WasteReport/v1": WasteReport,
    "RunComparison/v1": RunComparison,
    "ComparisonAxis/v1": ComparisonAxis,
    "ToolSurfaceAudit/v1": ToolSurfaceAudit,
    "SurfaceFinding/v1": SurfaceFinding,
    "ToolDisclosure/v1": ToolDisclosure,
    "ToolPage/v1": ToolPage,
    "PageWindow/v1": PageWindow,
    "ToolBenchmark/v1": ToolBenchmark,
    "ToolBenchmarkSample/v1": ToolBenchmarkSample,
    "ToolBenchmarkReport/v1": ToolBenchmarkReport,
    "DisclosurePolicy/v1": DisclosurePolicy,
    "ForgeCapabilityDescriptor/v1": ForgeCapabilityDescriptor,
    "ForgeTaskRequest/v1": ForgeTaskRequest,
    "ForgeTaskStatus/v1": ForgeTaskStatus,
    "ForgeTaskResult/v1": ForgeTaskResult,
    "ForgeEvidenceArtifact/v1": ForgeEvidenceArtifact,
    "ForgeEvidenceBundle/v1": ForgeEvidenceBundle,
    "ForgeHandoff/v1": ForgeHandoff,
    "ForgeHealth/v1": ForgeHealth,
    "TraceGradeDimension/v1": TraceGradeDimension,
    "TraceGrade/v1": TraceGrade,
    "TraceGradingReport/v1": TraceGradingReport,
    "LiveEvalLayer/v1": LiveEvalLayer,
    "LiveEvalReport/v1": LiveEvalReport,
    "FrontierPoint/v1": FrontierPoint,
    "QualityFrontier/v1": QualityFrontier,
    "AdversarialCaseResult/v1": AdversarialCaseResult,
    "SecurityAdversarialReport/v1": SecurityAdversarialReport,
    "MemoryEvalCaseResult/v1": MemoryEvalCaseResult,
    "MemoryEvalReport/v1": MemoryEvalReport,
    "CostVector/v1": CostVector,
    "LedgerRef/v1": LedgerRef,
    "RunLedgerEntry/v1": RunLedgerEntry,
    "BudgetEnvelope/v1": BudgetEnvelope,
    "EconomyPlan/v1": EconomyPlan,
    "LadderStep/v1": LadderStep,
    "RiskClassification/v1": RiskClassification,
    "CacheDep/v1": CacheDep,
    "CacheEntry/v1": CacheEntry,
    "CacheDecision/v1": CacheDecision,
    "DeltaSlice/v1": DeltaSlice,
    "ExpertiseSelection/v1": ExpertiseSelection,
    "RoleContextPlan/v1": RoleContextPlan,
    "PositionDelta/v1": PositionDelta,
    "RefereePacket/v1": RefereePacket,
    "ShadowDecision/v1": ShadowDecision,
    "AgentUniqueness/v1": AgentUniqueness,
    "TestSlice/v1": TestSlice,
    "ErrorSlice/v1": ErrorSlice,
    "ToolSurface/v1": ToolSurface,
    "HostProjection/v1": HostProjection,
    "EconomyMatrix/v1": EconomyMatrix,
    "EvaluationGate/v1": EvaluationGate,
    "ReplayReport/v1": ReplayReport,
    "RoleROI/v1": RoleROI,
    "InformationGain/v1": InformationGain,
    "VerificationPlan/v1": VerificationPlan,
    "RetrievalResult/v1": RetrievalResult,
    "EvidenceNode/v1": EvidenceNode,
    "EconomyDoctor/v1": EconomyDoctor,
    "ProviderCapability/v1": ProviderCapability,
    "TierDecision/v1": TierDecision,
    "PromptEnvelope/v1": PromptEnvelope,
    "LocalityPlan/v1": LocalityPlan,
    "FreshnessWatch/v1": FreshnessWatch,
    "LiveEvidenceDecision/v1": LiveEvidenceDecision,
    "VerificationEscalation/v1": VerificationEscalation,
    "PhaseBudgetPlan/v1": PhaseBudgetPlan,
    "EconomyCheckpoint/v1": EconomyCheckpoint,
    "ProofReceipt/v1": ProofReceipt,
    "BenchmarkIdentity/v1": BenchmarkIdentity,
}


def contract_names() -> list[str]:
    return sorted(CONTRACTS)


def contract_schema(name: str) -> dict[str, Any]:
    """The JSON schema of a registered contract — unknown names are refused."""
    model = CONTRACTS.get(name)
    if model is None:
        raise ContractError(
            "AF-CONTRACTS-UNKNOWN",
            f"no contract {name!r}; known: {contract_names()}",
        )
    return model.model_json_schema()
