"""Generate the knowledge-pack document set from real artifacts.

Every pack doc is derived from data the repo already holds — catalog
rules, source_authority entries, dispatch verbs, documented error codes
— never authored prose. Re-run after catalog changes: the docs are
checked in, and `knowledge check` requires their presence.

Usage: python scripts/gen_pack_docs.py [--root knowledge]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from apiforge.knowledge.loader import load_packs
from apiforge.rules.catalog import load_catalog

DOCS = (
    "index.md",
    "quick-reference.md",
    "concepts.md",
    "patterns.md",
    "anti-patterns.md",
    "recipes.md",
    "troubleshooting.md",
)


def _domain_tokens(domain: str) -> list[str]:
    return [t for t in domain.split("-") if len(t) > 2]


def _verbs_for(domain: str) -> list[str]:
    """Dispatch verbs whose name shares a token with the domain."""
    from apiforge.dispatch.runner import _VERBS

    tokens = _domain_tokens(domain)
    return sorted(v[0] for v in _VERBS if any(t in v[0] for t in tokens))


def _error_codes_for(domain: str, doc: str) -> list[tuple[str, str]]:
    tokens = _domain_tokens(domain)
    rows: list[tuple[str, str]] = []
    for line in doc.splitlines():
        m = re.match(r"\| `(AF-[A-Z0-9-]+)` \| (.+?) \|", line)
        if not m:
            continue
        code, desc = m.group(1), m.group(2)
        if any(t in code.lower() or t in desc.lower() for t in tokens):
            rows.append((code, desc))
    return rows


def _write(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    root = (
        Path(sys.argv[sys.argv.index("--root") + 1]) if "--root" in sys.argv else Path("knowledge")
    )
    packs = load_packs(root)
    catalog = load_catalog()
    error_doc = Path("docs/catalog-contract.md").read_text(encoding="utf-8")
    written = 0

    for domain, pack in sorted(packs.items()):
        d = root / domain
        rules = [catalog[rid] for rid in pack.rule_ids if rid in catalog]
        verbs = _verbs_for(domain)
        codes = _error_codes_for(domain, error_doc)
        header = (
            f"<!-- generated by scripts/gen_pack_docs.py from catalog + pack data -->\n"
            f"# {domain}\n\n{pack.summary}\n\n"
        )

        # index.md
        files = sorted(p.name for p in d.iterdir() if p.is_file())
        body = header + (
            f"Version: {pack.version} — verified: {pack.verified or 'never'}\n\n"
            f"Rule areas: {', '.join(pack.areas) or 'none'} — "
            f"rules: {len(rules)} — evals: {len(pack.evals)}\n\n"
            "## Files\n\n" + "".join(f"- `{f}`\n" for f in files)
        )
        written += _write(d / "index.md", body)

        # quick-reference.md
        body = header + "## Rules\n\n"
        if rules:
            body += "| Rule | Severity | Title |\n|---|---|---|\n" + "".join(
                f"| `{r.rule_id}` | {r.severity} | {r.title} |\n" for r in rules
            )
        else:
            body += "No executable rules yet — this pack indexes sources only.\n"
        written += _write(d / "quick-reference.md", body)

        # concepts.md
        body = (
            header
            + "## Source authority\n\n| Source | Authority | Verified |\n|---|---|---|\n"
            + "".join(f"| {s.name} | {s.authority} | {s.verified} |\n" for s in pack.sources)
            + "\nNormative claims cite these sources; nothing here overrides them.\n"
        )
        written += _write(d / "concepts.md", body)

        # patterns.md — what the platform can extract for this domain
        body = header + "## Extraction patterns\n\n"
        if verbs:
            body += "Verbs that produce facts for this domain:\n\n" + "".join(
                f"- `{v}`\n" for v in verbs
            )
        else:
            body += "No extractor verb covers this domain yet — the pack is a source index.\n"
        written += _write(d / "patterns.md", body)

        # anti-patterns.md — every rule detects one
        body = header + "## Detected anti-patterns\n\n"
        if rules:
            for r in rules:
                body += (
                    f"### `{r.rule_id}` — {r.title} ({r.severity})\n\n"
                    f"{r.rationale}\n\n"
                    f"Remediation: {r.remediation}\n\n"
                    f"Reference: {r.reference or 'none declared'}\n\n"
                )
        else:
            body += "No detected anti-patterns — this domain has no executable rules yet.\n"
        written += _write(d / "anti-patterns.md", body)

        # recipes.md
        body = header + "## Recipes\n\n"
        if verbs:
            body += "".join(f"- `apiforge {v} --path <dump-or-project>`\n" for v in verbs)
        body += (
            f"- `apiforge knowledge show {domain}`\n"
            f"- `apiforge judge` then filter findings by rules "
            f"{', '.join(pack.rule_ids) or '(none declared)'}\n"
        )
        written += _write(d / "recipes.md", body)

        # troubleshooting.md
        body = header + "## Error codes\n\n"
        if codes:
            body += "| Code | Meaning |\n|---|---|\n" + "".join(
                f"| `{c}` | {desc} |\n" for c, desc in codes
            )
        else:
            body += "No domain-specific error codes; generic codes apply.\n"
        written += _write(d / "troubleshooting.md", body)

        # evals.yaml — only when absent; hand-written probes always win
        evals_path = d / "evals.yaml"
        if not evals_path.is_file():
            if rules:
                lines = ["evals:"]
                for r in rules:
                    prompt = (f"An artifact shows: {r.title.lower()}. Which rule fires?").replace(
                        '"', "'"
                    )
                    lines += [
                        f"  - id: {domain}/{r.rule_id}",
                        f'    prompt: "{prompt}"',
                        f"    expect: {{kind: rule, id: {r.rule_id}}}",
                    ]
                _write(evals_path, "\n".join(lines) + "\n")
            else:
                _write(evals_path, "evals: []\n")
            written += 1

    print(f"packs={len(packs)} docs_written={written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
